## DataSource Properties
spring.datasource.url: jdbc:mysql://localhost:3306/blogdb
  ?useUnicode=true&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
spring.datasource.username: root
spring.datasource.password: testtest

## Hibernate Properties
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: validate