spring.datasource.url: jdbc:mysql://localhost:3306/blogdb
  ?useUnicode=true&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
spring.datasource.username: root
spring.datasource.password: testtest
#spring.jpa.hibernate.ddl-auto: none && create