## DataSource Properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blogdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.yandex.ru
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  ## Hibernate Properties
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate
    show-sql: true

  ##liquibase DBMigration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    #enable: false

server:
  port: ${PORT:8080}

##init config
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 961 500-94-94
  email: mitkiril@gmail.com
  copyright: Дмитрий Кириллов
  copyrightFrom: 2019

file:
  maxFileSize: 5_000_000
  width: 36
  height: 36

user:
  namePattern: ^[а-яА-ЯёЁa-zA-Z0-9]{2,20}$
  minLengthPassword: 6

password:
  linkPrefix: /login/change-password/
  lengthHash: 45

settings:
  value:
    true: YES
    false: NO

#Cloudinary configuration
cloud:
  name: atarikir #${CLOUD_NAME}
  key: 428158394967337 #${CLOUD_KEY}
  secret: mtNViiYD4NgAd0jqeX8lgBDKupE #${CLOUD_SECRET}