## DataSource Properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
    username: root
    password: testtest

## Hibernate Properties
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate
    show-sql: true

##liquibase DBMigration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    #enable: false

##init config
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 961 500-94-94
  email: mitkiril@gmail.com
  copyright: Дмитрий Кириллов
  copyrightFrom: 2021