## DataSource Properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
    username: root
    password: testtest
  mail:
    host: smtp.yandex.ru
    username: dmitrijkirilloff
    password: tco03acer
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  ## Hibernate Properties
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate
    show-sql: true

  ##liquibase DBMigration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    #enable: false

##init config
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 961 500-94-94
  email: mitkiril@gmail.com
  copyright: Дмитрий Кириллов
  copyrightFrom: 2021

##captcha config
captcha.deleteLimitTime: 1

file:
  uploadDirImage: ./upload
  uploadDirAvatar: ./avatars
  maxFileSize: 5_000_000
  width: 36
  height: 36

settings:
  code:
    multiuserMode: MULTIUSER_MODE
    postPremoderation: POST_PREMODERATION
    statisticsIsPublic: STATISTICS_IS_PUBLIC
  value:
    true: YES
    false: NO

user:
  namePattern: ^[а-яА-ЯёЁa-zA-Z0-9]{2,20}$
  minLengthPassword: 6
  errorEmail: Этот e-mail уже зарегистрирован
  errorName: Имя указано неверно
  errorPassword: Пароль короче 6-ти символов
  errorCaptcha: Код с картинки введён неверно
  errorPhoto: Фото слишком большое, нужно не более 5 Мб
  errorExtension: Файл не формата изображение jpg, png

